import { Sticker } from './types';

export const stickersData: Sticker[] = [
  {
    id: '1',
    name: 'Happy Dance',
    url: '/bubu-cute-dance-happy.gif',
    tags: ['happy', 'dance', 'excited'],
  },
  {
    id: '2',
    name: 'Love Heart',
    url: '/bubu-love-heart.gif',
    tags: ['love', 'heart', 'cute'],
  },
  {
    id: '3',
    name: 'Sleepy',
    url: '/bubu-sleep-sleepy.gif',
    tags: ['sleep', 'tired', 'relax'],
  },
  {
    id: '4',
    name: 'Eating Happy',
    url: '/bubu-eat-happy.gif',
    tags: ['eat', 'happy', 'food'],
  },
  {
    id: '5',
    name: 'Working',
    url: '/bubu-serious-pc-laptop-work.gif',
    tags: ['work', 'study', 'serious'],
  },
  {
    id: '6',
    name: 'Drink Milk Tea',
    url: '/bubu-drink-stab-mad-milktea.gif',
    tags: ['drink', 'boba', 'mad'],
  },
  {
    id: '7',
    name: 'Jump Excited',
    url: '/bubu-jump-excited-happy-scarf-cloth.gif',
    tags: ['excited', 'jump', 'happy'],
  },
  {
    id: '8',
    name: 'Question Confused',
    url: '/bubu-question-ask-confused-huh.gif',
    tags: ['confused', 'question', 'wonder'],
  },
  {
    id: '9',
    name: 'Laughing Naughty',
    url: '/bubu-laugh-naughty.gif',
    tags: ['laugh', 'happy', 'naughty'],
  },
  {
    id: '10',
    name: 'Cold Scared',
    url: '/bubu-cold-scared.gif',
    tags: ['cold', 'scared', 'nervous'],
  },
  {
    id: '11',
    name: 'Sad Cry',
    url: '/bubu-sad-cry.gif',
    tags: ['sad', 'cry', 'upset'],
  },
  {
    id: '12',
    name: 'Angry Mad',
    url: '/bubu-mad-angry.gif',
    tags: ['angry', 'mad', 'upset'],
  },
  {
    id: '13',
    name: 'Tired Hot',
    url: '/bubu-tired-hot-worried-sad-anxiety.gif',
    tags: ['tired', 'worried', 'sad'],
  },
  {
    id: '14',
    name: 'Speechless',
    url: '/bubu-speechless-nervous-scared.gif',
    tags: ['nervous', 'speechless', 'scared'],
  },
  {
    id: '15',
    name: 'Chair Full',
    url: '/bubu-chair-tummy-fat-full-sad.gif',
    tags: ['full', 'sad', 'tired'],
  },
  {
    id: '16',
    name: 'Swing Happy',
    url: '/bubu-swing-happy.gif',
    tags: ['happy', 'swing', 'play'],
  },
  {
    id: '17',
    name: 'Sit Fish Chill',
    url: '/bubu-sit-fish-boss-chill-play.gif',
    tags: ['chill', 'relax', 'play'],
  },
  {
    id: '18',
    name: 'Sleeping Tree',
    url: '/bubu-sleepy-sleep-tree-ball-bear.gif',
    tags: ['sleep', 'tired', 'relax'],
  },
  {
    id: '19',
    name: 'Cold Frozen',
    url: '/bubu-cold-nervous-anxious-awkward-sit-frozen-shocked.gif',
    tags: ['cold', 'nervous', 'shocked'],
  },
  {
    id: '20',
    name: 'Angry Boss',
    url: '/bubu-angry-boss-mad.gif',
    tags: ['angry', 'mad', 'boss'],
  },
  {
    id: '21',
    name: 'Ninja Angry',
    url: '/bubu-ninja-angry-mad-kill.gif',
    tags: ['angry', 'ninja', 'mad'],
  },
  {
    id: '22',
    name: 'Miss Dudu Bed',
    url: '/bubu-missdudu-bed.gif',
    tags: ['love', 'bed', 'miss'],
  },
  {
    id: '23',
    name: 'Eating Sleepy',
    url: '/bubu-eat-sleepy.gif',
    tags: ['eat', 'sleepy', 'tired'],
  },
  {
    id: '24',
    name: 'Sad Worried',
    url: '/bubu-sad-worried-frown.gif',
    tags: ['sad', 'worried', 'upset'],
  },
  {
    id: '25',
    name: 'Shine Excited',
    url: '/bubu-shine-excited-bed-gum.gif',
    tags: ['excited', 'happy', 'shine'],
  },
  {
    id: '26',
    name: 'Shoes Glow',
    url: '/bubu-shoes-glow-cloth.gif',
    tags: ['happy', 'glow', 'shoes'],
  },
  {
    id: '27',
    name: 'Pants Naughty',
    url: '/bubu-pants-shorts-naughty-cloth.gif',
    tags: ['naughty', 'happy', 'pants'],
  },
  {
    id: '28',
    name: 'Laugh Bag',
    url: '/bubu-laugh-naughty-bag-xd.gif',
    tags: ['laugh', 'happy', 'naughty'],
  },
  {
    id: '29',
    name: 'Happy Jump',
    url: '/bubu-happy-jump-excited.gif',
    tags: ['happy', 'jump', 'excited'],
  },
  {
    id: '30',
    name: 'Angry',
    url: '/bubu-angry.gif',
    tags: ['angry', 'mad', 'upset'],
  },
];
