import { Sticker } from './types';

export const stickersData: Sticker[] = [
  {
    id: '1',
    name: 'Happy Dance',
    url: '/bubu-cute-dance-happy.gif',
    tags: ['happy', 'dance', 'excited'],
  },
  {
    id: '2',
    name: 'Love Heart',
    url: '/bubu-love-heart.gif',
    tags: ['love', 'heart', 'cute'],
  },
  {
    id: '3',
    name: 'Sleepy',
    url: '/bubu-sleep-sleepy.gif',
    tags: ['sleep', 'tired', 'relax'],
  },
  {
    id: '4',
    name: 'Eating Happy',
    url: '/bubu-eat-happy.gif',
    tags: ['eat', 'happy', 'food'],
  },
  {
    id: '5',
    name: 'Working',
    url: '/bubu-serious-pc-laptop-work.gif',
    tags: ['work', 'study', 'serious'],
  },
  {
    id: '6',
    name: 'Drink Milk Tea',
    url: '/bubu-drink-stab-mad-milktea.gif',
    tags: ['drink', 'boba', 'mad'],
  },
  {
    id: '7',
    name: 'Jump Excited',
    url: '/bubu-jump-excited-happy-scarf-cloth.gif',
    tags: ['excited', 'jump', 'happy'],
  },
  {
    id: '8',
    name: 'Question Confused',
    url: '/bubu-question-ask-confused-huh.gif',
    tags: ['confused', 'question', 'wonder'],
  },
  {
    id: '9',
    name: 'Laughing Naughty',
    url: '/bubu-laugh-naughty.gif',
    tags: ['laugh', 'happy', 'naughty'],
  },
  {
    id: '10',
    name: 'Cold Scared',
    url: '/bubu-cold-scared.gif',
    tags: ['cold', 'scared', 'nervous'],
  },
  {
    id: '11',
    name: 'Sad Cry',
    url: '/bubu-sad-cry.gif',
    tags: ['sad', 'cry', 'upset'],
  },
  {
    id: '12',
    name: 'Angry Mad',
    url: '/bubu-mad-angry.gif',
    tags: ['angry', 'mad', 'upset'],
  },
  {
    id: '13',
    name: 'Tired Hot',
    url: '/bubu-tired-hot-worried-sad-anxiety.gif',
    tags: ['tired', 'worried', 'sad'],
  },
  {
    id: '14',
    name: 'Speechless',
    url: '/bubu-speechless-nervous-scared.gif',
    tags: ['nervous', 'speechless', 'scared'],
  },
  {
    id: '15',
    name: 'Chair Full',
    url: '/bubu-chair-tummy-fat-full-sad.gif',
    tags: ['full', 'sad', 'tired'],
  },
  {
    id: '16',
    name: 'Swing Happy',
    url: '/bubu-swing-happy.gif',
    tags: ['happy', 'swing', 'play'],
  },
  {
    id: '17',
    name: 'Sit Fish Chill',
    url: '/bubu-sit-fish-boss-chill-play.gif',
    tags: ['chill', 'relax', 'play'],
  },
  {
    id: '18',
    name: 'Sleeping Tree',
    url: '/bubu-sleepy-sleep-tree-ball-bear.gif',
    tags: ['sleep', 'tired', 'relax'],
  },
  {
    id: '19',
    name: 'Cold Frozen',
    url: '/bubu-cold-nervous-anxious-awkward-sit-frozen-shocked.gif',
    tags: ['cold', 'nervous', 'shocked'],
  },
  {
    id: '20',
    name: 'Angry Boss',
    url: '/bubu-angry-boss-mad.gif',
    tags: ['angry', 'mad', 'boss'],
  },
  {
    id: '21',
    name: 'Ninja Angry',
    url: '/bubu-ninja-angry-mad-kill.gif',
    tags: ['angry', 'ninja', 'mad'],
  },
  {
    id: '22',
    name: 'Miss Dudu Bed',
    url: '/bubu-missdudu-bed.gif',
    tags: ['love', 'bed', 'miss'],
  },
  {
    id: '23',
    name: 'Eating Sleepy',
    url: '/bubu-eat-sleepy.gif',
    tags: ['eat', 'sleepy', 'tired'],
  },
  {
    id: '24',
    name: 'Sad Worried',
    url: '/bubu-sad-worried-frown.gif',
    tags: ['sad', 'worried', 'upset'],
  },
  {
    id: '25',
    name: 'Shine Excited',
    url: '/bubu-shine-excited-bed-gum.gif',
    tags: ['excited', 'happy', 'shine'],
  },
  {
    id: '26',
    name: 'Shoes Glow',
    url: '/bubu-shoes-glow-cloth.gif',
    tags: ['happy', 'glow', 'shoes'],
  },
  {
    id: '27',
    name: 'Pants Naughty',
    url: '/bubu-pants-shorts-naughty-cloth.gif',
    tags: ['naughty', 'happy', 'pants'],
  },
  {
    id: '28',
    name: 'Laugh Bag',
    url: '/bubu-laugh-naughty-bag-xd.gif',
    tags: ['laugh', 'happy', 'naughty'],
  },
  {
    id: '29',
    name: 'Happy Jump',
    url: '/bubu-happy-jump-excited.gif',
    tags: ['happy', 'jump', 'excited'],
  },
  {
    id: '30',
    name: 'Angry',
    url: '/bubu-angry.gif',
    tags: ['angry', 'mad', 'upset'],
  },
  {
    id: '31',
    name: 'Beautiful Makeup',
    url: '/bubu-beautiful-pretty-lipstick-makeup.gif',
    tags: ['pretty', 'happy', 'makeup'],
  },
  {
    id: '32',
    name: 'Bed Dance',
    url: '/bubu-bed-liedown-happy-dance.gif',
    tags: ['happy', 'dance', 'bed'],
  },
  {
    id: '33',
    name: 'Bed Phone',
    url: '/bubu-bed-phone.gif',
    tags: ['phone', 'bed', 'relax'],
  },
  {
    id: '34',
    name: 'Bed Sleep Naughty',
    url: '/bubu-bed-sleep-naughty.gif',
    tags: ['sleep', 'naughty', 'bed'],
  },
  {
    id: '35',
    name: 'Bounce Happy',
    url: '/bubu-bounce-happy.gif',
    tags: ['happy', 'bounce', 'excited'],
  },
  {
    id: '36',
    name: 'Bully Dudu',
    url: '/bubu-bully-dudu-dudu-cry.gif',
    tags: ['bully', 'sad', 'cry'],
  },
  {
    id: '37',
    name: 'Cheeks Happy',
    url: '/bubu-cheeks-happy.gif',
    tags: ['happy', 'cute', 'cheeks'],
  },
  {
    id: '38',
    name: 'Cloth Bounce',
    url: '/bubu-cloth-bounce.gif',
    tags: ['bounce', 'happy', 'cloth'],
  },
  {
    id: '39',
    name: 'Cook Egg Fail',
    url: '/bubu-cook-egg-fail.gif',
    tags: ['cook', 'fail', 'sad'],
  },
  {
    id: '40',
    name: 'Drink Happy',
    url: '/bubu-drink-happy.gif',
    tags: ['drink', 'happy', 'relax'],
  },
  {
    id: '41',
    name: 'Eat Bite',
    url: '/bubu-eat-bite.gif',
    tags: ['eat', 'food', 'hungry'],
  },
  {
    id: '42',
    name: 'Fast Ride Pig',
    url: '/bubu-fast-ride-pig.gif',
    tags: ['fast', 'ride', 'excited'],
  },
  {
    id: '43',
    name: 'Food Icecream',
    url: '/bubu-food-icecream.gif',
    tags: ['food', 'icecream', 'happy'],
  },
  {
    id: '44',
    name: 'Gift Present',
    url: '/bubu-gift-present-happy-surprise.gif',
    tags: ['gift', 'happy', 'surprise'],
  },
  {
    id: '45',
    name: 'Happy Glow Jump',
    url: '/bubu-happy-glow-jump-excited.gif',
    tags: ['happy', 'excited', 'jump'],
  },
  {
    id: '46',
    name: 'Hide Worried',
    url: '/bubu-hide-worried.gif',
    tags: ['hide', 'worried', 'scared'],
  },
  {
    id: '47',
    name: 'Icecream Eat',
    url: '/bubu-icecream-eat.gif',
    tags: ['icecream', 'eat', 'happy'],
  },
  {
    id: '48',
    name: 'Lashes Pretty',
    url: '/bubu-lashes-pretty-happy.gif',
    tags: ['pretty', 'happy', 'cute'],
  },
  {
    id: '49',
    name: 'Leave Dudu Sad',
    url: '/bubu-leave-dudu-sad-cry.gif',
    tags: ['sad', 'cry', 'leave'],
  },
  {
    id: '50',
    name: 'Mad Knife Throw',
    url: '/bubu-mad-angry-knife-throw.gif',
    tags: ['mad', 'angry', 'knife'],
  },
  {
    id: '51',
    name: 'Read Tired',
    url: '/bubu-read-tired-sleepy.gif',
    tags: ['read', 'tired', 'sleepy'],
  },
  {
    id: '52',
    name: 'Sad Disappointed',
    url: '/bubu-sad-disappointed-worried.gif',
    tags: ['sad', 'disappointed', 'worried'],
  },
  {
    id: '53',
    name: 'Sad Missing Dudu',
    url: '/bubu-sad-missing-dudu.gif',
    tags: ['sad', 'miss', 'lonely'],
  },
  {
    id: '54',
    name: 'Sleep Tree',
    url: '/bubu-sleep-tree.gif',
    tags: ['sleep', 'tree', 'relax'],
  },
  {
    id: '55',
    name: 'Squish',
    url: '/bubu-squish.gif',
    tags: ['squish', 'cute', 'funny'],
  },
  {
    id: '56',
    name: 'Swing Carrot',
    url: '/bubu-swing-carrot-happy.gif',
    tags: ['swing', 'happy', 'carrot'],
  },
  {
    id: '57',
    name: 'Tease Happy',
    url: '/bubu-tease-happy.gif',
    tags: ['tease', 'happy', 'naughty'],
  },
  {
    id: '58',
    name: 'Troll Prank',
    url: '/bubu-troll-prank-naughty-happy-phone.gif',
    tags: ['troll', 'prank', 'naughty'],
  },
  {
    id: '59',
    name: 'Wake Dudu',
    url: '/bubu-wake-dudu.gif',
    tags: ['wake', 'morning', 'dudu'],
  },
  {
    id: '60',
    name: 'Workout Exercise',
    url: '/bubu-workout-exercise-fit.gif',
    tags: ['workout', 'exercise', 'fit'],
  },
  {
    id: '61',
    name: 'Sit Drink Happy',
    url: '/bubu-sit-drink-happy-feet.gif',
    tags: ['sit', 'drink', 'happy'],
  },
  {
    id: '62',
    name: 'BubuDudu Balloon',
    url: '/bubududu-balloon-fly.gif',
    tags: ['balloon', 'fly', 'happy'],
  },
  {
    id: '63',
    name: 'BubuDudu Cat',
    url: '/bubududu-cat.gif',
    tags: ['cat', 'cute', 'pet'],
  },
  {
    id: '64',
    name: 'BubuDudu Eat Full',
    url: '/bubududu-eat-happy-full.gif',
    tags: ['eat', 'full', 'happy'],
  },
  {
    id: '65',
    name: 'BubuDudu Goofy Dance',
    url: '/bubududu-goofy-dance-happy.gif',
    tags: ['dance', 'goofy', 'happy'],
  },
  {
    id: '66',
    name: 'BubuDudu Kiss',
    url: '/bubududu-kiss-happy.gif',
    tags: ['kiss', 'love', 'happy'],
  },
  {
    id: '67',
    name: 'BubuDudu Love Kiss',
    url: '/bubududu-love-kiss.gif',
    tags: ['love', 'kiss', 'romance'],
  },
  {
    id: '68',
    name: 'BubuDudu Mad Focus',
    url: '/bubududu-mad-focus-play.gif',
    tags: ['mad', 'focus', 'play'],
  },
  {
    id: '69',
    name: 'Dudu Fat',
    url: '/dudu-fat.gif',
    tags: ['fat', 'full', 'funny'],
  },
  {
    id: '70',
    name: 'Dudu Ghost',
    url: '/dudu-ghost.gif',
    tags: ['ghost', 'scared', 'funny'],
  },
  {
    id: '71',
    name: 'Dudu Gun Happy',
    url: '/dudu-gun-happy-excited.gif',
    tags: ['gun', 'happy', 'excited'],
  },
  {
    id: '72',
    name: 'Dudu Lift Bubu',
    url: '/dudu-lift-bubu-happy-love.gif',
    tags: ['lift', 'love', 'happy'],
  },
  {
    id: '73',
    name: 'Dudu Play Bubu',
    url: '/dudu-play-bubu-drink-love.gif',
    tags: ['play', 'drink', 'love'],
  },
  {
    id: '74',
    name: 'Dudu Sick Tired',
    url: '/dudu-sick-tired-worried-scared.gif',
    tags: ['sick', 'tired', 'worried'],
  },
  {
    id: '75',
    name: 'Dudu Wash Bubu',
    url: '/dudu-wash-bubu-care.gif',
    tags: ['wash', 'care', 'love'],
  },
  {
    id: '76',
    name: 'Angry Fuming',
    url: '/bubu-angry-mad-fuming-mald.gif',
    tags: ['angry', 'mad', 'fuming'],
  },
  {
    id: '77',
    name: 'Angry Madge Play',
    url: '/bubu-angry-madge-mad-play.gif',
    tags: ['angry', 'mad', 'play'],
  },
  {
    id: '78',
    name: 'Bath Relax',
    url: '/bubu-bath-relax.gif',
    tags: ['bath', 'relax', 'chill'],
  },
  {
    id: '79',
    name: 'Candy Eat',
    url: '/bubu-candy-eat.gif',
    tags: ['candy', 'eat', 'sweet'],
  },
  {
    id: '80',
    name: 'Cry Sad Scream',
    url: '/bubu-cry-sad-scream-beg.gif',
    tags: ['cry', 'sad', 'scream'],
  },
  {
    id: '81',
    name: 'Dizzy Sleepy',
    url: '/bubu-dizzy-sleepy-tired.gif',
    tags: ['dizzy', 'sleepy', 'tired'],
  },
  {
    id: '82',
    name: 'Dragon Mad',
    url: '/bubu-dragon-mad.gif',
    tags: ['dragon', 'mad', 'angry'],
  },
  {
    id: '83',
    name: 'Dragon Pink Angry',
    url: '/bubu-dragon-pink-angry-mad.gif',
    tags: ['dragon', 'pink', 'angry'],
  },
  {
    id: '84',
    name: 'Drink Christmas',
    url: '/bubu-drink-happy-excited-christmas-snow.gif',
    tags: ['drink', 'christmas', 'happy'],
  },
  {
    id: '85',
    name: 'Eat Candy Happy',
    url: '/bubu-eat-candy-happyt.gif',
    tags: ['eat', 'candy', 'happy'],
  },
  {
    id: '86',
    name: 'Excited Pray',
    url: '/bubu-excited-worried-glowing-pray.gif',
    tags: ['excited', 'pray', 'worried'],
  },
  {
    id: '87',
    name: 'Fan Happy Jump',
    url: '/bubu-fan-happy-excited-jump.gif',
    tags: ['fan', 'happy', 'excited'],
  },
  {
    id: '88',
    name: 'Fast Walk Pink',
    url: '/bubu-fastwalk-run-pink.gif',
    tags: ['fast', 'walk', 'run'],
  },
  {
    id: '89',
    name: 'Feed Eat Full',
    url: '/bubu-feed-eat-yum-full.gif',
    tags: ['feed', 'eat', 'full'],
  },
  {
    id: '90',
    name: 'Gum',
    url: '/bubu-gum.gif',
    tags: ['gum', 'chew', 'relax'],
  },
  {
    id: '91',
    name: 'Hat Dragon Cute',
    url: '/bubu-hat-dragon-cute.gif',
    tags: ['hat', 'dragon', 'cute'],
  },
  {
    id: '92',
    name: 'Hide Surprise',
    url: '/bubu-hide-surprise-happy.gif',
    tags: ['hide', 'surprise', 'happy'],
  },
  {
    id: '93',
    name: 'Motorcycle Speed',
    url: '/bubu-motorcycle-speed-mad.gif',
    tags: ['motorcycle', 'speed', 'mad'],
  },
  {
    id: '94',
    name: 'Naughty Love',
    url: '/bubu-naughty-love-saliva.gif',
    tags: ['naughty', 'love', 'kiss'],
  },
  {
    id: '95',
    name: 'Panty Naughty',
    url: '/bubu-panty-naughty.gif',
    tags: ['naughty', 'panty', 'funny'],
  },
  {
    id: '96',
    name: 'Sad Box Hide',
    url: '/bubu-sad-worried-box-hide.gif',
    tags: ['sad', 'worried', 'hide'],
  },
  {
    id: '97',
    name: 'Scared Nervous',
    url: '/bubu-scared-nervous.gif',
    tags: ['scared', 'nervous', 'worried'],
  },
  {
    id: '98',
    name: 'Sit Upside Down',
    url: '/bubu-sit-upsidedown-chair-dance-happy.gif',
    tags: ['sit', 'dance', 'happy'],
  },
  {
    id: '99',
    name: 'Sleep Wake',
    url: '/bubu-sleep-wake.gif',
    tags: ['sleep', 'wake', 'morning'],
  },
  {
    id: '100',
    name: 'Sunflower Dance',
    url: '/bubu-sunflower-dance.gif',
    tags: ['sunflower', 'dance', 'happy'],
  },
  {
    id: '101',
    name: 'Table Naughty',
    url: '/bubu-table-naughty-happy.gif',
    tags: ['table', 'naughty', 'happy'],
  },
  {
    id: '102',
    name: 'Travel Bag Walk',
    url: '/bubu-travel-bag-walk-cloth.gif',
    tags: ['travel', 'walk', 'bag'],
  },
  {
    id: '103',
    name: 'Witch Wizard',
    url: '/bubu-witch-wizard.gif',
    tags: ['witch', 'wizard', 'magic'],
  },
  {
    id: '104',
    name: 'Worried Blanket',
    url: '/bubu-worried-cold-blanket-bed-sad-nervous.gif',
    tags: ['worried', 'cold', 'sad'],
  },
  {
    id: '105',
    name: 'Worried Tired',
    url: '/bubu-worried-tired-poopie-scared.gif',
    tags: ['worried', 'tired', 'scared'],
  },
  {
    id: '106',
    name: 'Babies',
    url: '/bubu-babies.gif',
    tags: ['babies', 'cute', 'family'],
  },
  {
    id: '107',
    name: 'Baby Happy In Love',
    url: '/bubu-baby-happy-inlove-love.gif',
    tags: ['baby', 'love', 'happy'],
  },
  {
    id: '108',
    name: 'Baby Milk',
    url: '/bubu-baby-milk.gif',
    tags: ['baby', 'milk', 'drink'],
  },
  {
    id: '109',
    name: 'Baby Pat',
    url: '/bubu-baby-pat.gif',
    tags: ['baby', 'pat', 'cute'],
  },
  {
    id: '110',
    name: 'Baby Small',
    url: '/bubu-baby-small.gif',
    tags: ['baby', 'small', 'cute'],
  },
  {
    id: '111',
    name: 'Drink Milk Baby',
    url: '/bubu-drink-milk-baby.gif',
    tags: ['drink', 'milk', 'baby'],
  },
  {
    id: '112',
    name: 'Drinking Milk Excited',
    url: '/bubu-drinking-milk-excited.gif',
    tags: ['drinking', 'milk', 'excited'],
  },
  {
    id: '113',
    name: 'Excited Naughty Eyeglow',
    url: '/bubu-excited-naughty-eyeglow.gif',
    tags: ['excited', 'naughty', 'eyeglow'],
  },
  {
    id: '114',
    name: 'Exercise Bike',
    url: '/bubu-exercise-bike.gif',
    tags: ['exercise', 'bike', 'workout'],
  },
  {
    id: '115',
    name: 'Mad Ultimate',
    url: '/bubu-mad-ultimate-ss.gif',
    tags: ['mad', 'angry', 'ultimate'],
  },
  {
    id: '116',
    name: 'Milk Smile Happy',
    url: '/bubu-milk-smile-happy.gif',
    tags: ['milk', 'smile', 'happy'],
  },
  {
    id: '117',
    name: 'Nod Yes Baby',
    url: '/bubu-nod-yes-dudubaby.gif',
    tags: ['nod', 'yes', 'baby'],
  },
  {
    id: '118',
    name: 'Run Panic Scared',
    url: '/bubu-run-panic-scared.gif',
    tags: ['run', 'panic', 'scared'],
  },
  {
    id: '119',
    name: 'Sick Medicine',
    url: '/bubu-sick-medicine.gif',
    tags: ['sick', 'medicine', 'ill'],
  },
  {
    id: '120',
    name: 'Sleep Snoring',
    url: '/bubu-sleep-snor.gif',
    tags: ['sleep', 'snoring', 'tired'],
  },
  {
    id: '121',
    name: 'Suck Milk',
    url: '/bubu-suck-milk-cloth.gif',
    tags: ['suck', 'milk', 'baby'],
  },
  {
    id: '122',
    name: 'Upside Down Laugh',
    url: '/bubu-upsidedown-happy-laugh-naughty.gif',
    tags: ['upsidedown', 'laugh', 'naughty'],
  },
  {
    id: '123',
    name: 'Wink',
    url: '/bubu-wink.gif',
    tags: ['wink', 'cute', 'flirt'],
  },
  {
    id: '124',
    name: 'BubuDudu Family',
    url: '/bubududu-family.gif',
    tags: ['family', 'together', 'love'],
  },
  {
    id: '125',
    name: 'BubuDudu Happy Family',
    url: '/bubududu-happy-family.gif',
    tags: ['family', 'happy', 'love'],
  },
  {
    id: '126',
    name: 'BubuDudu Massage',
    url: '/bubududu-massage.gif',
    tags: ['massage', 'relax', 'care'],
  },
  {
    id: '127',
    name: 'Dudu Baby Blanket',
    url: '/dudu-baby-blanket-bed.gif',
    tags: ['dudu', 'baby', 'blanket'],
  },
  {
    id: '128',
    name: 'Dudu Baby',
    url: '/dudu-baby.gif',
    tags: ['dudu', 'baby', 'cute'],
  },
  {
    id: '129',
    name: 'Dudu Bring Bubu',
    url: '/dudu-bring-bubu.gif',
    tags: ['dudu', 'bring', 'care'],
  },
  {
    id: '130',
    name: 'Dudu Eat Chocolate',
    url: '/dudu-eat-chocolate-bite.gif',
    tags: ['dudu', 'eat', 'chocolate'],
  },
  {
    id: '131',
    name: 'Dudu Love Baby Bubu',
    url: '/dudu-love-happy-babybubu.gif',
    tags: ['dudu', 'love', 'baby'],
  },
  {
    id: '132',
    name: 'Dudu Okay Happy',
    url: '/dudu-okay-happy-excited.gif',
    tags: ['dudu', 'okay', 'happy'],
  },
  {
    id: '133',
    name: 'Dudu Scared Hug',
    url: '/dudu-scared-nervous-hug.gif',
    tags: ['dudu', 'scared', 'hug'],
  },
  {
    id: '134',
    name: 'Dudu Walk Fast Mad',
    url: '/dudu-walk-fast-mad.gif',
    tags: ['dudu', 'walk', 'mad'],
  },
  {
    id: '135',
    name: 'Dudu Want Milk',
    url: '/dudu-want-milk-drink.gif',
    tags: ['dudu', 'milk', 'want'],
  },
  {
    id: '136',
    name: 'Carry Dudu Hug',
    url: '/bubu-carry-dudu-hug.gif',
    tags: ['carry', 'hug', 'love'],
  },
  {
    id: '137',
    name: 'Cry Hug',
    url: '/bubu-cry-hug.gif',
    tags: ['cry', 'hug', 'sad'],
  },
  {
    id: '138',
    name: 'Hug Sad Dudu',
    url: '/bubu-hug-sad-dudu.gif',
    tags: ['hug', 'sad', 'comfort'],
  },
  {
    id: '139',
    name: 'Kiss Dudu Forehead Bed',
    url: '/bubu-kiss-dudu-forehead-bed.gif',
    tags: ['kiss', 'forehead', 'bed'],
  },
  {
    id: '140',
    name: 'Kiss Dudu In Bed',
    url: '/bubu-kiss-dudu-in-bed.gif',
    tags: ['kiss', 'bed', 'love'],
  },
  {
    id: '141',
    name: 'Pats Dudu Head Sleeping',
    url: '/bubu-pats-dudus-head-sleeping.gif',
    tags: ['pat', 'sleep', 'care'],
  },
  {
    id: '142',
    name: 'Runs Dudu Arm',
    url: '/bubu-runs-dudus-arm.gif',
    tags: ['run', 'arm', 'happy'],
  },
  {
    id: '143',
    name: 'Smooch Dudu',
    url: '/bubu-smooch-dudu.gif',
    tags: ['smooch', 'kiss', 'love'],
  },
  {
    id: '144',
    name: 'Squish Dudu Cheeks',
    url: '/bubu-squish-dudu-cheeks.gif',
    tags: ['squish', 'cheeks', 'cute'],
  },
  {
    id: '145',
    name: 'Squish Dudu',
    url: '/bubu-squish-dudu.gif',
    tags: ['squish', 'hug', 'love'],
  },
  {
    id: '146',
    name: 'Top of Dudu Bed',
    url: '/bubu-topofdudu-bed.gif',
    tags: ['bed', 'sleep', 'top'],
  },
  {
    id: '147',
    name: 'BubuDudu Bed Hug Sad Cry',
    url: '/bubududu-bed-hug-sad-cry-bubu.gif',
    tags: ['bed', 'hug', 'sad'],
  },
  {
    id: '148',
    name: 'BubuDudu Fan Sleep Window',
    url: '/bubududu-fan-sleep-window.gif',
    tags: ['fan', 'sleep', 'window'],
  },
  {
    id: '149',
    name: 'BubuDudu Happy Lovely Hug',
    url: '/bubududu-happy-lovely-hug.gif',
    tags: ['hug', 'happy', 'love'],
  },
  {
    id: '150',
    name: 'BubuDudu Hug Jump',
    url: '/bubududu-hug-jump.gif',
    tags: ['hug', 'jump', 'excited'],
  },
  {
    id: '151',
    name: 'BubuDudu Hug Spin',
    url: '/bubududu-hug-spin.gif',
    tags: ['hug', 'spin', 'love'],
  },
  {
    id: '152',
    name: 'BubuDudu Jump Hold Hands',
    url: '/bubududu-jump-hold-hands.gif',
    tags: ['jump', 'hands', 'happy'],
  },
  {
    id: '153',
    name: 'BubuDudu Jump Holds Hand',
    url: '/bubududu-jump-holds-hand.gif',
    tags: ['jump', 'hands', 'excited'],
  },
  {
    id: '154',
    name: 'BubuDudu Sleep Top Each Other',
    url: '/bubududu-sleep-topeach-other.gif',
    tags: ['sleep', 'together', 'cute'],
  },
  {
    id: '155',
    name: 'BubuDudu Walk Run Happy',
    url: '/bubududu-walk-run-happy.gif',
    tags: ['walk', 'run', 'happy'],
  },
  {
    id: '156',
    name: 'Dudu Carry Sleepy Bubu',
    url: '/dudu-carry-sleepy-bubu.gif',
    tags: ['dudu', 'carry', 'sleep'],
  },
  {
    id: '157',
    name: 'Dudu Hug Bubu Love',
    url: '/dudu-hug-bubu-love.gif',
    tags: ['dudu', 'hug', 'love'],
  },
  {
    id: '158',
    name: 'Dudu Hug Bubu',
    url: '/dudu-hug-bubu.gif',
    tags: ['dudu', 'hug', 'care'],
  },
  {
    id: '159',
    name: 'Dudu Kiss Bubu Cheeks',
    url: '/dudu-kiss-bubu-cheeks.gif',
    tags: ['dudu', 'kiss', 'cheeks'],
  },
  {
    id: '160',
    name: 'Dudu Pats Bubu Back',
    url: '/dudu-pats-dudu-back.gif',
    tags: ['dudu', 'pat', 'back'],
  },
  {
    id: '161',
    name: 'Dudu Pinch Squish Bubu Cheek',
    url: '/dudu-pinch-squish-bubus-cheek.gif',
    tags: ['dudu', 'pinch', 'cheek'],
  },
  {
    id: '162',
    name: 'Dudu Shake Bubu Hand',
    url: '/dudu-shake-bubu-hand.gif',
    tags: ['dudu', 'shake', 'hand'],
  },
  {
    id: '163',
    name: 'Dudu Sick',
    url: '/dudu-sick.gif',
    tags: ['dudu', 'sick', 'ill'],
  },
  {
    id: '164',
    name: 'Dudu Sleep On Top of Bubu',
    url: '/dudu-sleep-on-top-of-bubu.gif',
    tags: ['dudu', 'sleep', 'top'],
  },
  {
    id: '165',
    name: 'Dudu Smooch Bubu',
    url: '/dudu-smooch-bubu.gif',
    tags: ['dudu', 'smooch', 'kiss'],
  },
];
